on:
    push:
        tags:
            - '*'

name: Release a New Version

jobs:
    releaseandpublish:
        name: Release on Github and Publish on NPM
        runs-on: ubuntu-latest
        steps:
            - name: â¬‡ï¸ Checkout repo
              uses: actions/checkout@v3

            - name: â” Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  always-auth: true
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@crystallize'

            - name: ğŸ“¥ Download deps
              run: yarn install

            - name: ğŸ„ Run the tests
              run: yarn build && yarn test

            - name: ğŸ· Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: ğŸ“¢ Publish to NPM
              run: yarn publish --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
