on:
    push:
        tags:
            - '*'

name: Release a New Version

jobs:
    releaseandpublish:
        name: Release on Github and Publish on NPM
        runs-on: ubuntu-latest
        steps:
            - name: ‚¨áÔ∏è Checkout repo
              uses: actions/checkout@v3

            - name: ‚éî Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  always-auth: true
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@crystallize'

            - name: üì• Download deps
              run: yarn install

            - name: üèÑ Run the tests
              env:
                  CRYSTALLIZE_ACCESS_TOKEN_ID: ${{ secrets.CRYSTALLIZE_ACCESS_TOKEN_ID}}
                  CRYSTALLIZE_ACCESS_TOKEN_SECRET: ${{ secrets.CRYSTALLIZE_ACCESS_TOKEN_SECRET}}
              run: yarn build && yarn test

            - name: üè∑ Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: üì¢ Publish to NPM
              run: yarn publish --new-version ${GITHUB_REF#"refs/tags/"} --no-git-tag-version
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
